environment:
  nodejs_version: "6"
  COZY_URL:
    secure: uO9y1OhE9RrwDoYV5ewQPWITVjiTLzLO+dxhyOxpzoU=
  COZY_PASSPHRASE:
    secure: 6A0bzbjM06atb2sN15M0LToiGH1NkvXDh3tPzmbOrzI=

install:
  - cmd: appveyor-retry powershell Install-Product node $env:nodejs_version
  - cd cli
  - cmd: appveyor-retry yarn
  - cmd: appveyor-retry yarn bootstrap:remote
  - cd ..

build: off

test_script:
  - cd cli
  - yarn build
  - yarn test:unit

on_failure:
  - node --version
  - npm --version
  - yarn --version
